DST/Components/GeolocationFormToggleViewComponent.cs
using DST.Models.Extensions;
using DST.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace DST.Components
{
    public class GeolocationFormToggleViewComponent : ViewComponent
    {
        #region Constructors

        public GeolocationFormToggleViewComponent() { }

        #endregion

        #region Methods

        public IViewComponentResult Invoke(string formId, bool enabled = true)
        {
            if (string.IsNullOrWhiteSpace(formId))
            {
                formId = string.Empty;
            }

            FormToggleViewModel viewModel = new()
            {
                FormId = formId,
                EnabledState = enabled.Disabled()
            };

            return View("~/Views/Shared/_GeolocationFormTogglePartial.cshtml", viewModel);
        }

        #endregion
    }
}

DST/Components/GeolocationFormViewComponent.cs
using DST.Models.Builders;
using DST.Models.DomainModels;
using DST.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;

namespace DST.Components
{
    public class GeolocationFormViewComponent : ViewComponent
    {
        #region Fields

        private readonly IGeolocationBuilder _geoBuilder;

        #endregion

        #region Constructors

        public GeolocationFormViewComponent(IGeolocationBuilder geoBuilder)
        {
            _geoBuilder = geoBuilder;

            // Load the client geolocation, if any.
            _geoBuilder.Load();
        }

        #endregion

        #region Methods

        public IViewComponentResult Invoke(Dictionary<string, string> route, string actionMethod)
        {
            string timeZoneId = _geoBuilder.CurrentGeolocation.TimeZoneId;
            string defaultId = GeolocationModel.DefaultId;

            IEnumerable<SelectListItem> timeZones = TimeZoneInfo.GetSystemTimeZones()
                .OrderByDescending(t => t.Id == defaultId)
                .ThenBy(t => t.BaseUtcOffset.TotalHours)
                .Select(t => new SelectListItem(t.DisplayName, t.Id, t.Id == timeZoneId));

            GeolocationViewModel viewModel = new()
            {
                Geolocation = _geoBuilder.CurrentGeolocation,
                TimeZones = timeZones,
                Route = route,
                ActionMethod = actionMethod
            };

            return View("~/Views/Shared/_GeolocationFormPartial.cshtml", viewModel);
        }

        #endregion
    }
}

DST/Components/OptionsFormToggleViewComponent.cs
using DST.Models.Extensions;
using DST.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace DST.Components
{
    public class OptionsFormToggleViewComponent : ViewComponent
    {
        #region Constructors

        public OptionsFormToggleViewComponent() { }

        #endregion

        #region Methods

        public IViewComponentResult Invoke(string formId, bool enabled = true)
        {
            if (string.IsNullOrWhiteSpace(formId))
            {
                formId = string.Empty;
            }

            FormToggleViewModel viewModel = new()
            {
                FormId = formId,
                EnabledState = enabled.Disabled()
            };

            return View("~/Views/Shared/_OptionsFormTogglePartial.cshtml", viewModel);
        }

        #endregion
    }
}

DST/Controllers/TrackController.cs
using DST.Core.Observer;
using DST.Models.Builders;
using DST.Models.BusinessLogic;
using DST.Models.DataLayer.Repositories;
using DST.Models.DomainModels;
using DST.Models.Extensions;
using DST.Models.Routes;
using DST.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using DST.Core.Trajectory;
using DST.Core.TimeKeeper;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using DST.Core.Coordinate;

namespace DST.Controllers
{
    public class TrackController : Controller
    {
        #region Methods

        public IActionResult Index()
        {
            // Redirect to the Summary endpoint, with default route segments.
            return RedirectToAction("Summary");
        }

        [HttpPost]
        public IActionResult SubmitSummaryGeolocation(
            [FromServices] IGeolocationBuilder geoBuilder,
            GeolocationModel geolocation,
            TrackSummaryRoute values,
            bool reset = false)
        {
            // Check model state.
            if (!ModelState.IsValid)
            {
                // The view is not being re-rendered here, so any server-side validation messages will not be shown.
                return RedirectToAction("Summary", values.ToDictionary());
            }

            // Load the client geolocation, if any.
            geoBuilder.Load();

            if (reset)
            {
                // Reset geolocation and timezone to defaults.
                geoBuilder.CurrentGeolocation.Reset();
            }
            else
            {
                // Update geolocation and timezone.
                geoBuilder.CurrentGeolocation.SetGeolocation(geolocation);
            }

            // Save the geolocation in session and create a persistent cookie.
            geoBuilder.Save();

            return RedirectToAction("Summary", values.ToDictionary());
        }

        [HttpPost]
        public IActionResult SubmitPhaseGeolocation(
            [FromServices] IGeolocationBuilder geoBuilder,
            GeolocationModel geolocation,
            TrackPhaseRoute values,
            bool reset = false)
        {
            // Check model state.
            if (!ModelState.IsValid)
            {
                // The view is not being re-rendered here, so any server-side validation messages will not be shown.
                return RedirectToAction("Phase", values.ToDictionary());
            }

            // Load the client geolocation, if any.
            geoBuilder.Load();

            if (reset)
            {
                // Reset geolocation and timezone to defaults.
                geoBuilder.CurrentGeolocation.Reset();
            }
            else
            {
                // Update geolocation and timezone.
                geoBuilder.CurrentGeolocation.SetGeolocation(geolocation);
            }

            // Save the geolocation in session and create a persistent cookie.
            geoBuilder.Save();

            return RedirectToAction("Phase", values.ToDictionary());
        }

        [HttpPost]
        public IActionResult SubmitPeriodGeolocation(
            [FromServices] IGeolocationBuilder geoBuilder,
            GeolocationModel geolocation,
            TrackPeriodRoute values,
            bool reset = false)
        {
            // Check model state.
            if (!ModelState.IsValid)
            {
                // The view is not being re-rendered here, so any server-side validation messages will not be shown.
                return RedirectToAction("Period", values.ToDictionary());
            }

            // Load the client geolocation, if any.
            geoBuilder.Load();

            if (reset)
            {
                // Reset geolocation and timezone to defaults.
                geoBuilder.CurrentGeolocation.Reset();
            }
            else
            {
                // Update geolocation and timezone.
                geoBuilder.CurrentGeolocation.SetGeolocation(geolocation);
            }

            // Save the geolocation in session and create a persistent cookie.
            geoBuilder.Save();

            return RedirectToAction("Period", values.ToDictionary());
        }

        [HttpPost]
        public IActionResult SetAlgorithm(TrackSummaryRoute values, string algorithm)
        {
            values.SetAlgorithm(algorithm);

            return RedirectToAction("Summary", values.ToDictionary());
        }

        [HttpGet]
        public ViewResult Summary(
            [FromServices] ITrackUnitOfWork data,
            [FromServices] IGeolocationBuilder geoBuilder,
            TrackSummaryRoute values)
        {
            // Validate route values.
            values.Validate();

            // Load the client geolocation, if any.
            geoBuilder.Load();

            DsoModel dso = data.GetDso(values.Catalog, values.Id);
            SeasonModel season = data.GetSeason(dso);
            ConstellationModel constellation = data.GetConstellation(dso);
            Algorithm algorithm = Utilities.GetAlgorithm(values.Algorithm);

            IEnumerable<SelectListItem> algorithms = AlgorithmName.GetTextValuePairs().Select(
                i => new SelectListItem(i.Text, i.Value, i.Value == values.Algorithm));

            TrackSummaryViewModel viewModel = new()
            {
                Dso = dso,
                CurrentRoute = values,
                SummaryInfo = Utilities.GetSummaryInfo(dso, season, constellation, geoBuilder.CurrentGeolocation, algorithm),
                Algorithms = algorithms
            };

            return View(viewModel);
        }

        private static TrackPhaseViewModel GetPhaseViewModel(
            ITrackUnitOfWork data,
            IGeolocationBuilder geoBuilder,
            ITrackPhaseBuilder phaseBuilder,
            TrackPhaseRoute values,
            bool buildResults)
        {
            // Validate route values.
            values.Validate();

            // Load the client geolocation, if any.
            geoBuilder.Load();

            DsoModel dso = data.GetDso(values.Catalog, values.Id);
            Algorithm algorithm = Utilities.GetAlgorithm(values.Algorithm);
            FormatType format = Utilities.GetCoordinateFormat(values.CoordinateFormat);
            ILocalObserver localObserver = Utilities.GetLocalObserver(dso, geoBuilder.CurrentGeolocation, algorithm);
            ITrajectory trajectory = TrajectoryCalculator.Calculate(localObserver);

            PhaseResultsViewModel resultsModel = new();
            IEnumerable<SelectListItem> phases = System.Array.Empty<SelectListItem>();
            string selectedPhase = string.Empty;
            string message = string.Empty;
            AlertType messageType = AlertType.Default;

            if (trajectory is IRiseSetTrajectory)
            {
                selectedPhase = values.Phase;

                phases = PhaseName.GetTextValuePairs().Select(
                    i => new SelectListItem(i.Text, i.Value, i.Value == selectedPhase));
            }
            else if (trajectory is ICircumpolarTrajectory and not IVariableTrajectory)
            {
                message = Resources.DisplayText.TrackPhaseWarningCircumpolar;
                messageType = AlertType.Danger;
            }
            else if (trajectory is ICircumpolarTrajectory and IVariableTrajectory)
            {
                message = Resources.DisplayText.TrackPhaseWarningCircumpolarOffset;
                messageType = AlertType.Warning;
                selectedPhase = PhaseName.Apex.ToKebabCase();

                phases = PhaseName.GetTextValuePairs().Select(
                    i => new SelectListItem(i.Text, i.Value, i.Value == selectedPhase, i.Value != selectedPhase));
            }
            else
            {
                message = Resources.DisplayText.TrackPhaseWarningNeverRise;
                messageType = AlertType.Danger;
            }

            if (buildResults)
            {
                // Load the previous phase entry, if any.
                phaseBuilder.Load();

                // Calculate the phase tracking results if an entry was submitted.
                if (phaseBuilder.Current.IsReady)
                {
                    resultsModel = Utilities.GetPhaseResults(localObserver, format, phaseBuilder.Current);

                    // Force the client to resubmit the form.
                    phaseBuilder.Current.IsReady = false;
                    phaseBuilder.Save();
                }
            }

            IEnumerable<SelectListItem> algorithms = AlgorithmName.GetTextValuePairs().Select(
                i => new SelectListItem(i.Text, i.Value, i.Value == values.Algorithm));

            IEnumerable<SelectListItem> formats = CoordinateFormatName.GetTextValuePairs().Select(
                i => new SelectListItem(i.Text, i.Value, i.Value == values.CoordinateFormat));

            TrackPhaseViewModel viewModel = new()
            {
                Dso = dso,
                CurrentRoute = values,
                Algorithms = algorithms,
                CoordinateFormats = formats,
                Phases = phases,

                TrackForm = new TrackPhaseModel()
                {
                    Algorithm = values.Algorithm,
                    CoordinateFormat = values.CoordinateFormat,
                    Start = Utilities.GetClientDateTime(geoBuilder.CurrentGeolocation, values.Start),
                    Phase = selectedPhase,
                    IsTrackOnce = values.IsTrackOnce,
                    Cycles = values.Cycles
                },

                ResultsModel = resultsModel,
                Alert = new(message, messageType)
            };

            return viewModel;
        }

        [HttpPost]
        public IActionResult SubmitPhase(
            [FromServices] ITrackUnitOfWork data,
            [FromServices] IGeolocationBuilder geoBuilder,

DST/Views/Track/Phase.cshtml
@model TrackPhaseViewModel

@{
    ViewBag.Title = "Phase";
    Layout = "_BannerLayout";

    TrackPhaseRoute current = Model.CurrentRoute;
    TrackPhaseRoute routes = current.Clone();
}

@section scripts {
    <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/location.js"></script>
    <script src="~/js/misc.js"></script>
    <script src="~/js/phase-toggle.js"></script>
}

<div id="phaseOptionsModal" class="modal fade" tabindex="-1" aria-labelledby="phaseOptionsModalTitle">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 id="phaseOptionsModalTitle" class="modal-title user-select-none text-truncate">Phase Tracking</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            @if (Model.IsTrackingSupported())
            {
                <form id="form-phase" asp-action="SubmitPhase" asp-all-route-data="@routes.ToDictionary()" method="post" defaultbutton="form-phase-submit">
                    <div class="modal-body">
                        <div class="form-floating mb-3">
                            <select id="select-phase-algorithm" class="form-select text-truncate" asp-for="TrackForm.Algorithm" asp-items="@Model.Algorithms"></select>
                            <label class="form-label user-select-none" for="select-phase-algorithm">Timekeeping Algorithm</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input id="input-phase-start" class="form-control" asp-for="TrackForm.Start" type="datetime-local" value="@Model.TrackForm.GetSortableStart()" />
                            <label class="form-label user-select-none" for="input-phase-start">Start</label>
                            <span asp-validation-for="TrackForm.Start" class="text-danger"></span>
                        </div>
                        <div class="form-floating mb-3">
                            <select id="select-phase" class="form-select text-truncate" asp-for="TrackForm.Phase" asp-items="@Model.Phases"></select>
                            <label class="form-label user-select-none" for="select-phase">Phase</label>
                        </div>
                        <div class="mb-3">
                            <div class="form-check form-switch">
                                <input id="input-phase-single" class="form-check-input" data-bs-toggle="collapse" href="#phase-collapse" role="button"
                                       asp-for="TrackForm.IsTrackOnce" type="checkbox" checked="@Model.TrackForm.IsTrackOnce" onchange="phaseTrackOnce()" />
                                <label class="form-label d-block user-select-none text-truncate" for="input-phase-single">Track Once</label>
                            </div>
                        </div>
                        <div id="phase-collapse" class="collapse @current.TrackOnce.Show() mb-3">
                            <div class="form-floating">
                                <input id="input-phase-cycles" class="form-control text-truncate" asp-for="TrackForm.Cycles" type="number" value="@Model.TrackForm.Cycles"
                                       disabled="@Model.TrackForm.IsTrackOnce" />
                                <label class="form-label user-select-none" for="input-phase-cycles">Cycles</label>
                                <span asp-validation-for="TrackForm.Cycles" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-floating mb-3">
                            <select id="select-phase-format" class="form-select text-truncate" asp-for="TrackForm.CoordinateFormat" asp-items="@Model.CoordinateFormats"></select>
                            <label class="form-label user-select-none" for="select-phase-format">Results Format</label>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button id="form-phase-submit" class="btn btn-primary" type="submit">Track</button>
                    </div>
                </form>
            }
            else if (Model.HasMessage())
            {
                <div class="modal-body">
                    <partial name="_AlertMessagePartial" model="@Model.Alert"></partial>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
                </div>
            }
        </div>
    </div>
</div>

<vc:geolocation-form route="routes.ToDictionary() as Dictionary<string, string>" action-method="SubmitPhaseGeolocation"></vc:geolocation-form>

<div class="container-md pt-3">
    <div class="d-inline-block">
        <a class="btn btn-link d-flex flex-nowrap align-middle gap-2 w-auto" asp-controller="Search" asp-action="Index">
            <i class="bi bi-arrow-left"></i>
            <span class="text-truncate">Back to search</span>
        </a>
    </div>
</div>

<partial name="_DsoNameHeadingPartial" model="@Model.Dso" />

<div class="sticky-top-container container-sm px-1 py-2 p-sm-3 my-0 my-sm-3 my-md-5">
    <div class="d-flex flex-column flex-md-row gap-0 gap-sm-2 gap-md-3">
        <div class="flex-grow-1 order-1 order-md-0">
            <div id="phaseOptionsCollapse" class="collapse d-md-flex">
                <nav class="nav nav-pills d-flex flex-column flex-md-row gap-1 gap-md-2">
                    <a class="nav-item nav-link d-flex justify-content-between justify-content-md-center border"
                       asp-controller="Track" asp-action="Summary" asp-all-route-data="@routes.GetSummaryRoute().ToDictionary()">
                        <span>Summary</span>
                        <i class="bi bi-chevron-right d-md-none"></i>
                    </a>
                    <a class="nav-item nav-link d-none d-md-flex active">Phase</a>
                    <a class="nav-item nav-link d-flex justify-content-between justify-content-md-center border"
                       asp-controller="Track" asp-action="Period" asp-all-route-data="@routes.GetSummaryRoute().ToDictionary()">
                        <span>Period</span>
                        <i class="bi bi-chevron-right d-md-none"></i>
                    </a>
                </nav>
            </div>
        </div>
        <div class="d-flex flex-nowrap justify-content-between">
            <div class="d-flex d-md-none">
                <a class="btn btn-white d-flex flex-nowrap rounded-0 px-1" data-bs-toggle="collapse" href="#phaseOptionsCollapse" role="button"
                   aria-expanded="false" aria-controls="#phaseOptionsCollapse">
                    <i class="bi bi-three-dots-vertical me-1 me-sm-2"></i>
                    <span class="text-truncate">Phase</span>
                </a>
            </div>
            <div class="d-flex gap-0 gap-sm-2">
                <vc:options-form-toggle form-id="#phaseOptionsModal" enabled="@Model.IsTrackingSupported()"></vc:options-form-toggle>
                <vc:geolocation-form-toggle form-id="#geolocation-modal"></vc:geolocation-form-toggle>
            </div>
        </div>
    </div>
</div>

<div class="container pt-3">

    @if (Model.HasMessage())
    {
        <div class="mb-3">
            <partial name="_AlertMessagePartial" model="@Model.Alert"></partial>
        </div>
    }

    <div class="mb-5">
        @if (Model.HasResults())
        {
            <div id="phaseInfoAccordion" class="accordion mb-3">
                <div class="accordion-item">
                    <h2 id="phaseInfoAccordionHeading" class="accordion-header">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#phaseInfoAccordionCollapse"
                                aria-expanded="true" aria-controls="phaseInfoAccordionCollapse">
                            Track Information
                        </button>
                    </h2>
                    <div id="phaseInfoAccordionCollapse" class="accordion-collapse collapse show"
                            aria-labelledby="phaseInfoAccordionHeading" data-bs-parent="#phaseInfoAccordion">
                        <div class="accordion-body">
                            <div class="row mb-3">
                                <label class="col-sm-4 col-form-label">Timekeeper</label>
                                <div class="col-sm-8">@Model.ResultsModel.TimeKeeper</div>
                                <label class="col-sm-4 col-form-label">Time scale</label>
                                <div class="col-sm-8">@Model.ResultsModel.TimeScale</div>
                                <label class="col-sm-4 col-form-label">Start</label>
                                <div class="col-sm-8">@Model.ResultsModel.Start</div>
                                <label class="col-sm-4 col-form-label">Phase</label>
                                <div class="col-sm-8">@Model.ResultsModel.Phase</div>
                                <label class="col-sm-4 col-form-label">Cycles</label>
                                <div class="col-sm-8">@Model.ResultsModel.Cycles</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="table-responsive">
                <table class="table table-striped caption-top align-middle d-none d-sm-table">
                    <caption>Track results</caption>
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col" class="text-nowrap">Date/Time</th>
                            <th scope="col" class="text-nowrap">Altitude</th>
                            <th scope="col" class="text-nowrap">Azimuth</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int resultNumber = 1;
                            foreach (var result in Model.ResultsModel.Results)
                            {
                                if (result is not null)
                                {
                                    <tr>
                                        <th scope="row">@resultNumber</th>
                                        <td class="text-nowrap">@result.GetLocalDateTimeText()</td>
                                        <td class="text-nowrap">@result.GetAltitudeText()</td>
                                        <td class="text-nowrap">@result.GetAzimuthText()</td>
                                    </tr>
                                }
                                resultNumber++;
                            }
                        }
                    </tbody>
                </table>

                <table class="table table-striped caption-top align-middle d-table d-sm-none">
                    <caption>Track results</caption>
                    <tbody>
                        @{
                            foreach (var result in Model.ResultsModel.Results)
                            {
                                if (result is not null)
                                {
                                    <tr>
                                        <td class="py-3">
                                            <div class="mx-3">
                                                <h6 class="mb-2">@result.GetLocalDateTimeText()</h6>
                                                <p class="mb-0">@result.GetCoordinateText()</p>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            }
                        }
                    </tbody>
                </table>
            </div>
        }
        else
        {
            <div class="text-center bg-light" style="padding-top:120px;padding-bottom:120px;">
                @if (Model.IsTrackingSupported())
                {
                    <p>Click the button below to begin tracking.</p>
                    <a class="btn btn-primary rounded-0" role="button" data-bs-toggle="modal" href="#phaseOptionsModal">
                        <span class="text-truncate">Start here</span>
                    </a>
                }
                else
                {
                    <p>Phase tracking is not supported for this object at your location.</p>
                }
            </div>
        }
    </div>

</div>